=== austinmatherne-wk/Arelle/trr-3.0.1+2019-04-17/conformance-tests/tests.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema 
  xmlns:xs="http://www.w3.org/2001/XMLSchema" 
  targetNamespace="http://xbrl.org/2011/conformance-rendering/transforms" 
  xmlns:conf="http://xbrl.org/2011/conformance-rendering/transforms" 
  elementFormDefault="qualified"
  attributeFormDefault="unqualified">
        <xs:element name="testcase">
                <xs:complexType>
                        <xs:sequence>
                                <xs:element ref="conf:transform" maxOccurs="unbounded"/>
                        </xs:sequence>
                        <xs:attribute name="target" type="xs:string"/>
                </xs:complexType>
        </xs:element>
        <xs:element name="transform">
                <xs:complexType>
                        <xs:sequence>
                                <xs:element ref="conf:variation" maxOccurs="unbounded"/>
                        </xs:sequence>
                        <xs:attribute name="name" type="xs:string"/>
                        <xs:attribute name="outputType" type="xs:QName"/>
                </xs:complexType>
        </xs:element>
        <xs:element name="variation">
                <xs:complexType>
                        <xs:attribute name="input" type="xs:string"  use="required"/>
                        <xs:attribute name="output" type="xs:string" use="required"/>
                        <xs:attribute name="result" use="optional">
                                <xs:simpleType>
                                        <xs:restriction base="xs:token">
                                                <xs:enumeration value="valid"/>
                                                <xs:enumeration value="invalid"/>
                                        </xs:restriction>
                                </xs:simpleType>
                        </xs:attribute>
                        <xs:attribute name="description" type="xs:string" use="optional"/>
                </xs:complexType>
        </xs:element>

        <!-- used when extracting valid/invalid variations --> 
        <xs:element name="variations">
                <xs:complexType>
                        <xs:sequence>
                          <xs:element name="input" type="xs:string" maxOccurs="unbounded"/>
                        </xs:sequence>
                        <xs:attribute name="result" use="optional"/>
                </xs:complexType>
        </xs:element>
</xs:schema>

=== austinmatherne-wk/Arelle/trr-3.0.1+2019-04-17/conformance-tests/tests.xml
<?xml version='1.0' encoding='UTF-8'?>
<?xml-stylesheet type='text/xsl' href='tests.xsl'?>
<testcase
  xmlns="http://xbrl.org/2011/conformance-rendering/transforms"
  xmlns:case="http://xbrl.org/2011/conformance-rendering/transforms" 
  xmlns:ixt="http://www.xbrl.org/inlineXBRL/transformation/2015-02-26"
  xmlns:xs="http://www.w3.org/2001/XMLSchema"
  target="http://www.xbrl.org/inlineXBRL/transformation/2015-02-26"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://xbrl.org/2011/conformance-rendering/transforms tests.xsd"
  >
  <!--
       Invalidity in these tests refers to the input data, not
       to the output value.  The output value should only be 
       provided for inputs which are valid and then they should
       always be the correct output values.
       -->

  <transform name="ixt:booleanfalse" outputType="xs:boolean">
      <variation input="Anydata" output="false" result="valid" />
      <variation input="偽"      output="false" result="valid" />
      <variation input="" output="false" result="valid" description="Empty input"/>
  </transform>

  <transform name="ixt:booleantrue" outputType="xs:boolean">
      <variation input="Anydata" output="true" result="valid" />
      <variation input="真"      output="true" result="valid" />
      <variation input="" output="true" result="valid" description="Empty input"/>
  </transform>

  <transform name="ixt:datedaymonth" outputType="xs:gMonthDay">
      <variation input="13/08" output="--08-13" result="valid" />
      <variation input="3/8" output="--08-03" result="valid" description="Single digit day and month" />
      <variation input="13.08" output="--08-13" result="valid" description="Alternative separator" />
      <variation input="13-08" output="--08-13" result="valid" />
      <variation input="13 08" output="--08-13" result="valid" />
      <variation input="13\08" output="--08-13" result="valid" />
      <variation input="13!08" output="--08-13" result="valid" />
      <variation input="13,08" output="--08-13" result="valid" />
      <variation input="13 / 08" output="--08-13" result="valid" description="More than one character separator" />
      <variation input="13asdf08" output="--08-13" result="valid" />
      <variation input="13 monkeys landed on the moon in '08" output="--08-13" result="valid" />
      <variation input="30/02" output="" result="invalid" description="Invalid xs:gMonthDay" />
  </transform>

  <transform name="ixt:datedaymonthdk"  outputType="xs:gMonthDay">
      <variation input="25. Sep."       output="--09-25" result="valid" />
      <variation input="25. sep."       output="--09-25" result="valid" />
      <variation input="25. september"  output="--09-25" result="valid" />
      <variation input="25. sepxxxxxx"  output="--09-25" result="valid"   description="The month is spelled incorrectly but the date will still be accepted as a valid transformation input." />
      <variation input="13. august"     output="--08-13" result="valid" />
      <variation input="13. SEP"        output="--09-13" result="valid" />
      <variation input="13. AUGUST"     output="--08-13" result="valid" />
      <variation input="1. august"      output="--08-01" result="valid" />
      <variation input="01. august"     output="--08-01" result="valid" />
      <variation input="13 AUGUST"      output="--08-13" result="valid"   description="The missing ordinalisation is unusual in Danish practice but will still be accepted as a valid transformation input." />
      <variation input="13 august"      output="--08-13" result="valid"   description="The missing ordinalisation is unusual in Danish practice but will still be accepted as a valid transformation input." />
      <variation input="13. August"     output="--08-13" result="valid" />
      <variation input="13. Aug"        output="--08-13" result="valid" />
      <variation input="13. AUG."       output="--08-13" result="valid" />
      <variation input="13. SEPT"       output="--09-13" result="valid" /><!-- corrected from 08-13 -->
      <variation input="13. augustsss"  output="--08-13" result="valid"   description="The month is spelled incorrectly but the date will still be accepted as a valid transformation input." />
      <variation input="13. august 12"  output=""        result="invalid" description="Trailing numeric characters are not accepted." />
      <variation input="25. september." output=""        result="invalid" description="There are too many characters and the string will not be accepted as a valid transformation input." />
      <variation input="30. februar"    output=""        result="invalid" description="Invalid xs:gMonthDay" />
      <variation input="22. of august"  output="--08-22" result="valid"   description="There are extra characters but the date will still be accepted as a valid transformation input." />
      <variation input="1.august"       output="--08-01" result="valid"   description="There is a missing delimiter but the date will still be accepted as a valid transformation input." />
      <variation input="1august"        output=""        result="invalid" description="There is a missing delimiter and the date will not be accepted as a valid transformation input." />
  </transform>

  <transform name="ixt:datedaymonthen" outputType="xs:gMonthDay">
      <variation input="13 August" output="--08-13" result="valid" />
      <variation input="13 Aug"    output="--08-13" result="valid" />
      <variation input="22nd of August"    output="--08-22" result="valid" />
      <variation input="1&#x02e2;&#x1d57; of August"    output="--08-01" result="valid" description="unicode superscript"/>
      <variation input="13 AUGUST" output="--08-13" result="valid" description="Capitalised long form" />
      <variation input="13 AUG" output="--08-13" result="valid" description="Capitalised short form" />
      <variation input="1 August" output="--08-01" result="valid" description="Single digit day" />
      <variation input="01 August" output="--08-01" result="valid" description="Day beginning with 0" />
      <variation input="30th day of January, March and April" output="--04-30" result="valid" description="Month as separator" />
      <variation input="13 SEPT"    output="" result="invalid" />
      <variation input="13 Augusts" output="" result="invalid" />
      <variation input="22nd day of August, which is the sixth month"    output="" result="invalid" />
      <variation input="13 august" output="" result="invalid" description="Lower case not permitted" />
      <variation input="30th February" output="" result="invalid" description="Invalid xs:gMonthDay" />
  </transform>

  <transform name="ixt:datedaymonthyear" outputType="xs:date">
      <variation input="13/08/32" output="2032-08-13" result="valid" />
      <variation input="13.08.32" output="2032-08-13" result="valid" />
      <variation input="8.8.32" output="2032-08-08" result="valid" description="Single digit day and month" />
      <variation input="13.08.3" output="2003-08-13" result="valid" description="Single digit year" />
      <variation input="13.08.1998" output="1998-08-13" result="valid" description="Four digit year" />
      <variation input="01.08.32" output="2032-08-01" result="valid" description="Day beginning with 0" />
      <variation input="13.08.0203" output="0203-08-13" result="valid" description="Year beginning with 0" />
      <variation input="13.08.03" output="2003-08-13" result="valid" description="Year beginning with 0" />
      <variation input="13.08.00" output="2000-08-13" result="valid" description="Millenium roll test" />
      <variation input="13.08.203" output="" result="invalid" description="Three digit year" />
      <variation input="30.02.09" output="" result="invalid" description="Invalid xs:date" />
  </transform>

  <transform name="ixt:datedaymonthyeardk" outputType="xs:date">
      <variation input="25. Sep. 2012"      output="2012-09-25" result="valid" />
      <variation input="25. sep. 2012"      output="2012-09-25" result="valid" />
      <variation input="25. september 2012" output="2012-09-25" result="valid" />
      <variation input="25. september 12"   output="2012-09-25" result="valid" />
      <variation input="25. september 2"    output="2002-09-25" result="valid" />
      <variation input="1. august 0203"     output="0203-08-01" result="valid" />
      <variation input="13. august 00"      output="2000-08-13" result="valid" />
      <variation input="13. august 0"       output="2000-08-13" result="valid" />
      <variation input="13. august 2012"    output="2012-08-13" result="valid" />
      <variation input="13. SEP 2012"       output="2012-09-13" result="valid" />
      <variation input="13. AUGUST 2012"    output="2012-08-13" result="valid" />
      <variation input="1. august 2012"     output="2012-08-01" result="valid" />
      <variation input="01. august 2012"    output="2012-08-01" result="valid" />
      <variation input="13 AUGUST 2012"     output="2012-08-13" result="valid"   description="The missing ordinalisation is unusual in Danish practice but will be accepted as a valid transformation input." />
      <variation input="1 august 2012"      output="2012-08-01" result="valid"   description="The missing ordinalisation is unusual in Danish practice but will be accepted as a valid transformation input." />
      <variation input="13. August 2012"    output="2012-08-13" result="valid" />
      <variation input="13. Aug 2012"       output="2012-08-13" result="valid" />
      <variation input="13. AUG. 2012"      output="2012-08-13" result="valid" />
      <variation input="13. SEPT 2012"      output="2012-09-13" result="valid"   description="The month abbreviation is unusual in Danish practice but will be accepted as a valid transformation input." />
